runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  MYSQL_HOST: 'db4free.net'
  MYSQL_USER: 'devahsan804'
  MYSQL_PASSWORD: 'Kalilinux2001@.'
  MYSQL_DB: 'todo_app12'

runtime_config:
  python_version: 3.9
